# Generated by Django 4.2.10 on 2024-02-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('status', '-priority', '-due_date')},
        ),
        migrations.AlterModelOptions(
            name='projectmodule',
            options={'ordering': ('completed', '-priority', '-due_date')},
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
